name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: ap-south-1a
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: s3sbdemo
  APP_NAME: app_sbdemo
  ENV_NAME: prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: "adopt"
        cache: maven
        

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install EB CLI
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip -y
        sudo pip3 install awsebcli

    - name: Create Elastic Beanstalk Application Version
      run: |
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ env.AWS_REGION }}
        aws s3 cp target/my-app.jar s3://${{ env.S3_BUCKET }}/
        aws elasticbeanstalk create-application-version --application-name ${{ env.APP_NAME }} --version-label ${{ github.sha }} --source-bundle S3Bucket="${{ env.S3_BUCKET }}",S3Key="my-app.jar"

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk update-environment --application-name ${{ env.APP_NAME }} --environment-name ${{ env.ENV_NAME }} --version-label ${{ github.sha }}

